apiVersion: v1
kind: Service
metadata:
  name: complete-prod-e2e-pipeline-svc
  labels:
    run: complete-prod-e2e-pipeline-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
  selector:
    run: complete-prod-e2e-pipeline